### ISSUE TITLE
npm start in win 64bit,has errors

### ISSUE THREAD

**Issue by moxiaobei2** [ryanflorence/react-project#54]
I follows your step,every step is oK,But run:npm run start , it did't work;
and throw errors like this,please give me some help^=^

0 info it worked if it ends with ok
1 verbose cli [ 'E:\nodejs\node.exe',
1 verbose cli   'E:\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reactTest@1.0.0~prestart: reactTest@1.0.0
6 silly lifecycle reactTest@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle reactTest@1.0.0~start: reactTest@1.0.0
8 verbose lifecycle reactTest@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle reactTest@1.0.0~start: PATH: E:\nodejs\node_modules\npm\bin\node-gyp-bin;I:\project\nodejsproject\react\reactTest\node_modules.bin;E:\nodejs;i:\server\imagemagick-6.2.7-q16;G:\Windows\system32;G:\Windows;G:\Windows\System32\Wbem;G:\Windows\System32\WindowsPowerShell\v1.0\;G:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\nodejs\;E:\TortoiseSVN\bin;E:\Git\cmd;E:\TortoiseGit\bin;E:\SecureFX\;E:\ImageMagick-7.0.2-Q16;E:\Python\Python36;I:\server\ImageMagick-6.2.7-Q16\;G:\Program Files\Microsoft SQL Server\110\Tools\Binn\;G:\Windows\system32\config\systemprofile.dnx\bin;G:\Program Files\Microsoft DNX\Dnvm\;I:\server\memcached;G:\Users\Administrator\AppData\Roaming\npm
10 verbose lifecycle reactTest@1.0.0~start: CWD: I:\project\nodejsproject\react\reactTest
11 silly lifecycle reactTest@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev' ]
12 silly lifecycle reactTest@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle reactTest@1.0.0~start: Failed to exec start script
14 verbose stack Error: reactTest@1.0.0 start: `if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (E:\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (E:\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid reactTest@1.0.0
16 verbose cwd I:\project\nodejsproject\react\reactTest
17 error Windows_NT 6.1.7601
18 error argv "E:\nodejs\node.exe" "E:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "start"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error reactTest@1.0.0 start: `if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev`
22 error Exit status 1
23 error Failed at the reactTest@1.0.0 start script 'if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the reactTest package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs reactTest
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls reactTest
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by wdjungst** [comment]
What version of node?

**Comment by jsfowles** [comment]
I'm also getting similar with MacOS.  I'm using Node 6.4.0 and npm 3.10.3.

Here is my error:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "react-project:start:dev"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! the-best-app-ever@1.0.0 react-project:start:dev: `eslint modules && react-project start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-best-app-ever@1.0.0 react-project:start:dev script 'eslint modules && react-project start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the the-best-app-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint modules && react-project start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs the-best-app-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls the-best-app-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AgaetisTakk/Desktop/projects/open_source/the-best-app-ever/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! the-best-app-ever@1.0.0 start: `if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-best-app-ever@1.0.0 start script 'if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the the-best-app-ever package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs the-best-app-ever
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls the-best-app-ever
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/AgaetisTakk/Desktop/projects/open_source/the-best-app-ever/npm-debug.log

**Comment by sudarshan89** [comment]
Simiar issue with 64bit Ubuntu machine.

> sudarshan@sudarshan-NC01U:~/work/sourcecode/github/weather-app$ npm run start
> 
> > weather-app@1.0.0 start /home/sudarshan/work/sourcecode/github/weather-app
> > if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev
> > 
> > weather-app@1.0.0 react-project:start:dev /home/sudarshan/work/sourcecode/github/weather-app
> > eslint modules && react-project start
> 
> [react-project] [start] task
> [react-project] checking app dependencies
> [react-project] NODE_ENV=development
> /home/sudarshan/work/sourcecode/github/weather-app/node_modules/react-project/lib/build.js:53
>     if (err) throw err;
>              ^
> 
> TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.dirname (path.js:1324:5)
>     at /home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:36
>     at /home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:22
>     at Array.map (native)
>     at OptionManager.resolvePresets (/home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
>     at OptionManager.mergePresets (/home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
>     at OptionManager.mergeOptions (/home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328:14)
>     at /home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:14
>     at /home/sudarshan/work/sourcecode/github/weather-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:390:24
> 
> npm ERR! Linux 4.4.0-34-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "react-project:start:dev"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> npm ERR! weather-app@1.0.0 react-project:start:dev: `eslint modules && react-project start`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the weather-app@1.0.0 react-project:start:dev script 'eslint modules && react-project start'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the weather-app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     eslint modules && react-project start
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs weather-app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls weather-app
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/sudarshan/work/sourcecode/github/weather-app/npm-debug.log
> 
> npm ERR! Linux 4.4.0-34-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
> npm ERR! node v6.2.0
> npm ERR! npm  v3.8.9
> npm ERR! code ELIFECYCLE
> npm ERR! weather-app@1.0.0 start: `if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the weather-app@1.0.0 start script 'if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the weather-app package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     if-env NODE_ENV=production && npm run react-project:start:prod || npm run react-project:start:dev
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs weather-app
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls weather-app
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/sudarshan/work/sourcecode/github/weather-app/npm-debug.log

`

**Comment by wdjungst** [comment]
I am also getting errors on Node 6 when I switch to Node 5 I am not getting any errors I will have to investigate this further
